(cl:defpackage detect_field-srv
  (:use )
  (:export
   "STARTLOOKINGFORCLOCKSTART"
   "<STARTLOOKINGFORCLOCKSTART-REQUEST>"
   "STARTLOOKINGFORCLOCKSTART-REQUEST"
   "<STARTLOOKINGFORCLOCKSTART-RESPONSE>"
   "STARTLOOKINGFORCLOCKSTART-RESPONSE"
  ))

