// Generated by gencpp from file detect_field/Clockstart.msg
// DO NOT EDIT!


#ifndef DETECT_FIELD_MESSAGE_CLOCKSTART_H
#define DETECT_FIELD_MESSAGE_CLOCKSTART_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detect_field
{
template <class ContainerAllocator>
struct Clockstart_
{
  typedef Clockstart_<ContainerAllocator> Type;

  Clockstart_()
    : hasClockStarted(false)
    , durationSinceStart(0)  {
    }
  Clockstart_(const ContainerAllocator& _alloc)
    : hasClockStarted(false)
    , durationSinceStart(0)  {
  (void)_alloc;
    }



   typedef uint8_t _hasClockStarted_type;
  _hasClockStarted_type hasClockStarted;

   typedef int32_t _durationSinceStart_type;
  _durationSinceStart_type durationSinceStart;





  typedef boost::shared_ptr< ::detect_field::Clockstart_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detect_field::Clockstart_<ContainerAllocator> const> ConstPtr;

}; // struct Clockstart_

typedef ::detect_field::Clockstart_<std::allocator<void> > Clockstart;

typedef boost::shared_ptr< ::detect_field::Clockstart > ClockstartPtr;
typedef boost::shared_ptr< ::detect_field::Clockstart const> ClockstartConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detect_field::Clockstart_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detect_field::Clockstart_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace detect_field

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'detect_field': ['/home/jeanette/catkin_ws/src/detect_field/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::detect_field::Clockstart_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detect_field::Clockstart_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_field::Clockstart_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_field::Clockstart_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_field::Clockstart_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_field::Clockstart_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detect_field::Clockstart_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6013aafddfc4fdbecb9ef87f99a88972";
  }

  static const char* value(const ::detect_field::Clockstart_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6013aafddfc4fdbeULL;
  static const uint64_t static_value2 = 0xcb9ef87f99a88972ULL;
};

template<class ContainerAllocator>
struct DataType< ::detect_field::Clockstart_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detect_field/Clockstart";
  }

  static const char* value(const ::detect_field::Clockstart_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detect_field::Clockstart_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool hasClockStarted\n\
int32 durationSinceStart\n\
";
  }

  static const char* value(const ::detect_field::Clockstart_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detect_field::Clockstart_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hasClockStarted);
      stream.next(m.durationSinceStart);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Clockstart_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detect_field::Clockstart_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detect_field::Clockstart_<ContainerAllocator>& v)
  {
    s << indent << "hasClockStarted: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hasClockStarted);
    s << indent << "durationSinceStart: ";
    Printer<int32_t>::stream(s, indent + "  ", v.durationSinceStart);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECT_FIELD_MESSAGE_CLOCKSTART_H
