// Generated by gencpp from file detect_field/RedLineSight.msg
// DO NOT EDIT!


#ifndef DETECT_FIELD_MESSAGE_REDLINESIGHT_H
#define DETECT_FIELD_MESSAGE_REDLINESIGHT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detect_field
{
template <class ContainerAllocator>
struct RedLineSight_
{
  typedef RedLineSight_<ContainerAllocator> Type;

  RedLineSight_()
    : sightedALine(false)
    , durationSinceSighting(0)
    , lapNum(0)
    , sightedFinish(false)  {
    }
  RedLineSight_(const ContainerAllocator& _alloc)
    : sightedALine(false)
    , durationSinceSighting(0)
    , lapNum(0)
    , sightedFinish(false)  {
  (void)_alloc;
    }



   typedef uint8_t _sightedALine_type;
  _sightedALine_type sightedALine;

   typedef int32_t _durationSinceSighting_type;
  _durationSinceSighting_type durationSinceSighting;

   typedef int32_t _lapNum_type;
  _lapNum_type lapNum;

   typedef uint8_t _sightedFinish_type;
  _sightedFinish_type sightedFinish;





  typedef boost::shared_ptr< ::detect_field::RedLineSight_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detect_field::RedLineSight_<ContainerAllocator> const> ConstPtr;

}; // struct RedLineSight_

typedef ::detect_field::RedLineSight_<std::allocator<void> > RedLineSight;

typedef boost::shared_ptr< ::detect_field::RedLineSight > RedLineSightPtr;
typedef boost::shared_ptr< ::detect_field::RedLineSight const> RedLineSightConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detect_field::RedLineSight_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detect_field::RedLineSight_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace detect_field

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'detect_field': ['/home/jeanette/catkin_ws/src/detect_field/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::detect_field::RedLineSight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detect_field::RedLineSight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_field::RedLineSight_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_field::RedLineSight_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_field::RedLineSight_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_field::RedLineSight_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detect_field::RedLineSight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ef155747a6bf23ba0e1bc1f460ec9a6";
  }

  static const char* value(const ::detect_field::RedLineSight_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ef155747a6bf23bULL;
  static const uint64_t static_value2 = 0xa0e1bc1f460ec9a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::detect_field::RedLineSight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detect_field/RedLineSight";
  }

  static const char* value(const ::detect_field::RedLineSight_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detect_field::RedLineSight_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool sightedALine\n\
int32 durationSinceSighting\n\
int32 lapNum\n\
bool sightedFinish\n\
\n\
";
  }

  static const char* value(const ::detect_field::RedLineSight_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detect_field::RedLineSight_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sightedALine);
      stream.next(m.durationSinceSighting);
      stream.next(m.lapNum);
      stream.next(m.sightedFinish);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RedLineSight_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detect_field::RedLineSight_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detect_field::RedLineSight_<ContainerAllocator>& v)
  {
    s << indent << "sightedALine: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sightedALine);
    s << indent << "durationSinceSighting: ";
    Printer<int32_t>::stream(s, indent + "  ", v.durationSinceSighting);
    s << indent << "lapNum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lapNum);
    s << indent << "sightedFinish: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sightedFinish);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECT_FIELD_MESSAGE_REDLINESIGHT_H
