// Generated by gencpp from file detect_field/StartLookingForClockstartRequest.msg
// DO NOT EDIT!


#ifndef DETECT_FIELD_MESSAGE_STARTLOOKINGFORCLOCKSTARTREQUEST_H
#define DETECT_FIELD_MESSAGE_STARTLOOKINGFORCLOCKSTARTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detect_field
{
template <class ContainerAllocator>
struct StartLookingForClockstartRequest_
{
  typedef StartLookingForClockstartRequest_<ContainerAllocator> Type;

  StartLookingForClockstartRequest_()
    : startLooking(0)  {
    }
  StartLookingForClockstartRequest_(const ContainerAllocator& _alloc)
    : startLooking(0)  {
  (void)_alloc;
    }



   typedef int32_t _startLooking_type;
  _startLooking_type startLooking;





  typedef boost::shared_ptr< ::detect_field::StartLookingForClockstartRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detect_field::StartLookingForClockstartRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartLookingForClockstartRequest_

typedef ::detect_field::StartLookingForClockstartRequest_<std::allocator<void> > StartLookingForClockstartRequest;

typedef boost::shared_ptr< ::detect_field::StartLookingForClockstartRequest > StartLookingForClockstartRequestPtr;
typedef boost::shared_ptr< ::detect_field::StartLookingForClockstartRequest const> StartLookingForClockstartRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detect_field::StartLookingForClockstartRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detect_field::StartLookingForClockstartRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace detect_field

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'detect_field': ['/home/jeanette/catkin_ws/src/detect_field/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::detect_field::StartLookingForClockstartRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detect_field::StartLookingForClockstartRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_field::StartLookingForClockstartRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_field::StartLookingForClockstartRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_field::StartLookingForClockstartRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_field::StartLookingForClockstartRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detect_field::StartLookingForClockstartRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "badba37d60f4729c39665c8312073b95";
  }

  static const char* value(const ::detect_field::StartLookingForClockstartRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbadba37d60f4729cULL;
  static const uint64_t static_value2 = 0x39665c8312073b95ULL;
};

template<class ContainerAllocator>
struct DataType< ::detect_field::StartLookingForClockstartRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detect_field/StartLookingForClockstartRequest";
  }

  static const char* value(const ::detect_field::StartLookingForClockstartRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detect_field::StartLookingForClockstartRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 startLooking\n\
";
  }

  static const char* value(const ::detect_field::StartLookingForClockstartRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detect_field::StartLookingForClockstartRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.startLooking);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartLookingForClockstartRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detect_field::StartLookingForClockstartRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detect_field::StartLookingForClockstartRequest_<ContainerAllocator>& v)
  {
    s << indent << "startLooking: ";
    Printer<int32_t>::stream(s, indent + "  ", v.startLooking);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECT_FIELD_MESSAGE_STARTLOOKINGFORCLOCKSTARTREQUEST_H
