// Generated by gencpp from file detect_field/StartLookingForClockstart.msg
// DO NOT EDIT!


#ifndef DETECT_FIELD_MESSAGE_STARTLOOKINGFORCLOCKSTART_H
#define DETECT_FIELD_MESSAGE_STARTLOOKINGFORCLOCKSTART_H

#include <ros/service_traits.h>


#include <detect_field/StartLookingForClockstartRequest.h>
#include <detect_field/StartLookingForClockstartResponse.h>


namespace detect_field
{

struct StartLookingForClockstart
{

typedef StartLookingForClockstartRequest Request;
typedef StartLookingForClockstartResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartLookingForClockstart
} // namespace detect_field


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::detect_field::StartLookingForClockstart > {
  static const char* value()
  {
    return "0a1c11a0caab3357eeba3d0bd2e33f82";
  }

  static const char* value(const ::detect_field::StartLookingForClockstart&) { return value(); }
};

template<>
struct DataType< ::detect_field::StartLookingForClockstart > {
  static const char* value()
  {
    return "detect_field/StartLookingForClockstart";
  }

  static const char* value(const ::detect_field::StartLookingForClockstart&) { return value(); }
};


// service_traits::MD5Sum< ::detect_field::StartLookingForClockstartRequest> should match 
// service_traits::MD5Sum< ::detect_field::StartLookingForClockstart > 
template<>
struct MD5Sum< ::detect_field::StartLookingForClockstartRequest>
{
  static const char* value()
  {
    return MD5Sum< ::detect_field::StartLookingForClockstart >::value();
  }
  static const char* value(const ::detect_field::StartLookingForClockstartRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::detect_field::StartLookingForClockstartRequest> should match 
// service_traits::DataType< ::detect_field::StartLookingForClockstart > 
template<>
struct DataType< ::detect_field::StartLookingForClockstartRequest>
{
  static const char* value()
  {
    return DataType< ::detect_field::StartLookingForClockstart >::value();
  }
  static const char* value(const ::detect_field::StartLookingForClockstartRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::detect_field::StartLookingForClockstartResponse> should match 
// service_traits::MD5Sum< ::detect_field::StartLookingForClockstart > 
template<>
struct MD5Sum< ::detect_field::StartLookingForClockstartResponse>
{
  static const char* value()
  {
    return MD5Sum< ::detect_field::StartLookingForClockstart >::value();
  }
  static const char* value(const ::detect_field::StartLookingForClockstartResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::detect_field::StartLookingForClockstartResponse> should match 
// service_traits::DataType< ::detect_field::StartLookingForClockstart > 
template<>
struct DataType< ::detect_field::StartLookingForClockstartResponse>
{
  static const char* value()
  {
    return DataType< ::detect_field::StartLookingForClockstart >::value();
  }
  static const char* value(const ::detect_field::StartLookingForClockstartResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DETECT_FIELD_MESSAGE_STARTLOOKINGFORCLOCKSTART_H
