// Generated by gencpp from file detect_field/StartLookingForClockstartResponse.msg
// DO NOT EDIT!


#ifndef DETECT_FIELD_MESSAGE_STARTLOOKINGFORCLOCKSTARTRESPONSE_H
#define DETECT_FIELD_MESSAGE_STARTLOOKINGFORCLOCKSTARTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detect_field
{
template <class ContainerAllocator>
struct StartLookingForClockstartResponse_
{
  typedef StartLookingForClockstartResponse_<ContainerAllocator> Type;

  StartLookingForClockstartResponse_()
    : startedLooking(0)  {
    }
  StartLookingForClockstartResponse_(const ContainerAllocator& _alloc)
    : startedLooking(0)  {
  (void)_alloc;
    }



   typedef int32_t _startedLooking_type;
  _startedLooking_type startedLooking;





  typedef boost::shared_ptr< ::detect_field::StartLookingForClockstartResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detect_field::StartLookingForClockstartResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StartLookingForClockstartResponse_

typedef ::detect_field::StartLookingForClockstartResponse_<std::allocator<void> > StartLookingForClockstartResponse;

typedef boost::shared_ptr< ::detect_field::StartLookingForClockstartResponse > StartLookingForClockstartResponsePtr;
typedef boost::shared_ptr< ::detect_field::StartLookingForClockstartResponse const> StartLookingForClockstartResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detect_field::StartLookingForClockstartResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detect_field::StartLookingForClockstartResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace detect_field

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'detect_field': ['/home/jeanette/catkin_ws/src/detect_field/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::detect_field::StartLookingForClockstartResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detect_field::StartLookingForClockstartResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_field::StartLookingForClockstartResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_field::StartLookingForClockstartResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_field::StartLookingForClockstartResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_field::StartLookingForClockstartResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detect_field::StartLookingForClockstartResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9915a01cb85cc9946c7785eee74b608b";
  }

  static const char* value(const ::detect_field::StartLookingForClockstartResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9915a01cb85cc994ULL;
  static const uint64_t static_value2 = 0x6c7785eee74b608bULL;
};

template<class ContainerAllocator>
struct DataType< ::detect_field::StartLookingForClockstartResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detect_field/StartLookingForClockstartResponse";
  }

  static const char* value(const ::detect_field::StartLookingForClockstartResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detect_field::StartLookingForClockstartResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 startedLooking\n\
\n\
";
  }

  static const char* value(const ::detect_field::StartLookingForClockstartResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detect_field::StartLookingForClockstartResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.startedLooking);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartLookingForClockstartResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detect_field::StartLookingForClockstartResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detect_field::StartLookingForClockstartResponse_<ContainerAllocator>& v)
  {
    s << indent << "startedLooking: ";
    Printer<int32_t>::stream(s, indent + "  ", v.startedLooking);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECT_FIELD_MESSAGE_STARTLOOKINGFORCLOCKSTARTRESPONSE_H
