<?xml version="1.0"?>

<!-- chaosbot: robot for 2018 SparkFun AVC Challenge in the Logisitics Class category -->
<robot name="chaosbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width_base" value="0.2" /> <!-- Rectangular dimensions (widthxdepth) of base -->
  <xacro:property name="depth_base" value="0.4" /> <!-- Rectangular dimensions (widthxdepth) of base -->
  <xacro:property name="length_wheelaxle" value="0.4" /> <!-- Dimensions (lengthxradius) of wheel axles -->
  <xacro:property name="radius_wheelaxle" value="0.05" /> <!-- Rectangular dimensions (lengthxradius) of base -->
  <xacro:property name="width_wheel" value="0.1" /> <!-- Dimensions (widthxradius) of wheels -->
  <xacro:property name="radius_wheel" value="0.15" /> <!-- Dimension (widthxradius) of wheels -->

  <xacro:property name="width_beams" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height_base" value="0.1" /> <!-- Robot Base -->
  <xacro:property name="height_chest" value="2" /> <!-- Chest -->
  <xacro:property name="height_bicep" value="1" /> <!-- Bicep -->
  <xacro:property name="height_forearm" value="1" /> <!-- Forearm -->
  <xacro:property name="height_hand" value="1" /> <!-- Hand -->
  <xacro:property name="camera_size" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find bot_definition)/urdf/chaosbot.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find bot_definition)/urdf/materials.xacro" />

  <!-- Robot Base -->
  <link name="base">
    <collision>
      <origin xyz="0 0 ${height_base/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width_base} ${depth_base} ${height_base}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 ${height_base/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width_base} ${depth_base} ${height_base}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <origin xyz="0 0 ${height_base/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width_base*depth_base + height_base*height_base)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height_base*height_base + width_base*depth_base)}" iyz="0.0"
	  izz="${mass / 12.0 * (width_base*depth_base + width_base*depth_base)}"/>
    </inertial>
  </link>

  <!-- Front wheel axle -->
  <link name="front_wheelaxle">
    <collision>
      <origin xyz="${length_wheelaxle/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${length_wheelaxle}" radius="${radius_wheelaxle}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${length_wheelaxle/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${length_wheelaxle}" radius="${radius_wheelaxle}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <origin xyz="${length_wheelaxle/2} 0 0" rpy="0 0 0"/>
      <mass value="1e-5" />
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="base_to_front_wheelaxle" type="fixed">
    <parent link="base"/>
    <child link="front_wheelaxle"/>
    <origin xyz="0 ${-width_base} ${-radius_wheelaxle}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Front left wheel -->
  <link name="front_left_wheel">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${width_wheel}" radius="${radius_wheel}"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${width_wheel}" radius="${radius_wheel}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="${width_wheel/2} 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="0.0" ixy="0.0" ixz="0.0"
	  iyy="0.0" iyz="0.0"
	  izz="0.0"/>
    </inertial>
  </link>
  <joint name="front_left_wheel_joint" type="continuous">
    <parent link="front_wheelaxle"/>
    <child link="front_left_wheel"/>
    <origin rpy="0 0 0" xyz="${-length_wheelaxle/2} 0 0"/>
    <axis rpy="0 0 0" xyz="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Front right wheel -->
  <link name="front_right_wheel">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${width_wheel}" radius="${radius_wheel}"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${width_wheel}" radius="${radius_wheel}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="${width_wheel/2} 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="0.0" ixy="0.0" ixz="0.0"
	  iyy="0.0" iyz="0.0"
	  izz="0.0"/>
    </inertial>
  </link>
  <joint name="front_right_wheel_joint" type="continuous">
    <parent link="front_wheelaxle"/>
    <child link="front_right_wheel"/>
    <origin rpy="0 0 0" xyz="${length_wheelaxle/2} 0 0"/>
    <axis rpy="0 0 0" xyz="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Back wheel axle -->
  <link name="back_wheelaxle">
    <collision>
      <origin xyz="${length_wheelaxle/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${length_wheelaxle}" radius="${radius_wheelaxle}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="${length_wheelaxle/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${length_wheelaxle}" radius="${radius_wheelaxle}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <inertial>
      <origin xyz="${length_wheelaxle/2} 0 0" rpy="0 0 0"/>
      <mass value="1e-5" />
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
  <joint name="base_to_back_wheelaxle" type="fixed">
    <parent link="base"/>
    <child link="back_wheelaxle"/>
    <origin xyz="0 ${-width_base} ${-radius_wheelaxle}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Back left wheel -->
  <link name="back_left_wheel">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${width_wheel}" radius="${radius_wheel}"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${width_wheel}" radius="${radius_wheel}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="${width_wheel/2} 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="0.0" ixy="0.0" ixz="0.0"
	  iyy="0.0" iyz="0.0"
	  izz="0.0"/>
    </inertial>
  </link>
  <joint name="back_left_wheel_joint" type="continuous">
    <parent link="back_wheelaxle"/>
    <child link="back_left_wheel"/>
    <origin rpy="0 0 0" xyz="${length_wheelaxle/2} 0 0"/>
    <axis rpy="0 0 0" xyz="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Back right wheel -->
  <link name="back_right_wheel">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${width_wheel}" radius="${radius_wheel}"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${width_wheel}" radius="${radius_wheel}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <origin xyz="${width_wheel/2} 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="0.0" ixy="0.0" ixz="0.0"
	  iyy="0.0" iyz="0.0"
	  izz="0.0"/>
    </inertial>
  </link>
  <joint name="back_right_wheel_joint" type="continuous">
    <parent link="back_wheelaxle"/>
    <child link="back_right_wheel"/>
    <origin rpy="0 0 0" xyz="${length_wheelaxle/2} 0 0"/>
    <axis rpy="0 0 0" xyz="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>


  <joint name="camera_mount_front" type="continuous">
    <parent link="base"/>
    <child link="camera_front"/>
    <origin xyz="0 ${width_base/2} ${width_base}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Front camera -->
  <link name="camera_front">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_size} ${camera_size} ${camera_size}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${camera_size} ${camera_size} ${camera_size}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
  <!-- generate an optical frame http://www.ros.org/reps/rep-0103.html#suffix-frames
      so that ros and opencv can operate on the camera frame correctly -->
  <link name="camera_front_optical">
  </link>
  <joint name="camera_optical_joint" type="fixed">
    <!-- these values have to be these values otherwise the gazebo camera image
        won't be aligned properly with the frame it is supposedly originating from -->
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    <parent link="camera_front"/>
    <child link="camera_front_optical"/>
  </joint>




</robot>
